// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventManger.proto

package EventManagerGRPC;

public interface DateRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extrasmart.DateRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 start_date = 1;</code>
   */
  long getStartDate();

  /**
   * <code>int64 end_date = 2;</code>
   */
  long getEndDate();
}
