// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventManger.proto

package EventManagerGRPC;

public final class SmartServiceImpl {
  private SmartServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrasmart_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrasmart_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrasmart_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrasmart_EventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrasmart_EventModificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrasmart_EventModificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrasmart_DateRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrasmart_DateRange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021EventManger.proto\022\nextrasmart\"D\n\005Event" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013descriptio" +
      "n\030\003 \001(\t\022\014\n\004date\030\005 \001(\003\"1\n\rEventResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"W\n\030Even" +
      "tModificationRequest\022\n\n\002id\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\014\n\004date\030\006 \001(" +
      "\003\"1\n\tDateRange\022\022\n\nstart_date\030\001 \001(\003\022\020\n\010en" +
      "d_date\030\002 \001(\0032\332\001\n\014EventManager\022:\n\010AddEven" +
      "t\022\021.extrasmart.Event\032\031.extrasmart.EventR" +
      "esponse\"\000\022R\n\013ModifyEvent\022$.extrasmart.Ev" +
      "entModificationRequest\032\031.extrasmart.Even" +
      "tResponse\"\000(\001\022:\n\nListEvents\022\025.extrasmart" +
      ".DateRange\032\021.extrasmart.Event\"\0000\001B&\n\020Eve" +
      "ntManagerGRPCB\020SmartServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extrasmart_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extrasmart_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrasmart_Event_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Date", });
    internal_static_extrasmart_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extrasmart_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrasmart_EventResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_extrasmart_EventModificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_extrasmart_EventModificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrasmart_EventModificationRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Date", });
    internal_static_extrasmart_DateRange_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_extrasmart_DateRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrasmart_DateRange_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
