// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventManager.proto

package EventManager_GRPC;

public interface DateRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extra_smart.DateRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 start_date = 1;</code>
   */
  long getStartDate();

  /**
   * <code>int64 end_date = 2;</code>
   */
  long getEndDate();
}
