// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventManager.proto

package EventManager_GRPC;

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extra_smart.EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
