// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventManger.proto

package EventManager_GRPC;

public final class SmartServiceImpl {
  private SmartServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_EventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_EventModificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_EventModificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_DateRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_DateRange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021EventManger.proto\022\013extra_smart\"D\n\005Even" +
      "t\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013descripti" +
      "on\030\003 \001(\t\022\014\n\004date\030\005 \001(\003\"1\n\rEventResponse\022" +
      "\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"W\n\030Eve" +
      "ntModificationRequest\022\n\n\002id\030\001 \001(\t\022\014\n\004nam" +
      "e\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\014\n\004date\030\006 \001" +
      "(\003\"1\n\tDateRange\022\022\n\nstart_date\030\001 \001(\003\022\020\n\010e" +
      "nd_date\030\002 \001(\0032\340\001\n\014EventManager\022<\n\010AddEve" +
      "nt\022\022.extra_smart.Event\032\032.extra_smart.Eve" +
      "ntResponse\"\000\022T\n\013ModifyEvent\022%.extra_smar" +
      "t.EventModificationRequest\032\032.extra_smart" +
      ".EventResponse\"\000(\001\022<\n\nListEvents\022\026.extra" +
      "_smart.DateRange\032\022.extra_smart.Event\"\0000\001" +
      "B\'\n\021EventManager_GRPCB\020SmartServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extra_smart_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extra_smart_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_Event_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Date", });
    internal_static_extra_smart_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extra_smart_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_EventResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_extra_smart_EventModificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_extra_smart_EventModificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_EventModificationRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Date", });
    internal_static_extra_smart_DateRange_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_extra_smart_DateRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_DateRange_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
