// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduelOptimizer.proto

package ScheduleOptimizerGRPC;

public interface GoalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extrasmart.Goal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float ideal_balance = 1;</code>
   */
  float getIdealBalance();

  /**
   * <code>int64 end_date = 2;</code>
   */
  long getEndDate();
}
