// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduelOptimizer.proto

package ScheduleOptimizerGRPC;

/**
 * Protobuf type {@code extrasmart.Goal}
 */
public  final class Goal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:extrasmart.Goal)
    GoalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Goal.newBuilder() to construct.
  private Goal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Goal() {
    idealBalance_ = 0F;
    endDate_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Goal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            idealBalance_ = input.readFloat();
            break;
          }
          case 16: {

            endDate_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ScheduleOptimizerGRPC.SmartServiceImpl.internal_static_extrasmart_Goal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ScheduleOptimizerGRPC.SmartServiceImpl.internal_static_extrasmart_Goal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ScheduleOptimizerGRPC.Goal.class, ScheduleOptimizerGRPC.Goal.Builder.class);
  }

  public static final int IDEAL_BALANCE_FIELD_NUMBER = 1;
  private float idealBalance_;
  /**
   * <code>float ideal_balance = 1;</code>
   */
  public float getIdealBalance() {
    return idealBalance_;
  }

  public static final int END_DATE_FIELD_NUMBER = 2;
  private long endDate_;
  /**
   * <code>int64 end_date = 2;</code>
   */
  public long getEndDate() {
    return endDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idealBalance_ != 0F) {
      output.writeFloat(1, idealBalance_);
    }
    if (endDate_ != 0L) {
      output.writeInt64(2, endDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idealBalance_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, idealBalance_);
    }
    if (endDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, endDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ScheduleOptimizerGRPC.Goal)) {
      return super.equals(obj);
    }
    ScheduleOptimizerGRPC.Goal other = (ScheduleOptimizerGRPC.Goal) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getIdealBalance())
        == java.lang.Float.floatToIntBits(
            other.getIdealBalance()));
    result = result && (getEndDate()
        == other.getEndDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDEAL_BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIdealBalance());
    hash = (37 * hash) + END_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndDate());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ScheduleOptimizerGRPC.Goal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ScheduleOptimizerGRPC.Goal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ScheduleOptimizerGRPC.Goal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScheduleOptimizerGRPC.Goal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ScheduleOptimizerGRPC.Goal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code extrasmart.Goal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:extrasmart.Goal)
      ScheduleOptimizerGRPC.GoalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduleOptimizerGRPC.SmartServiceImpl.internal_static_extrasmart_Goal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduleOptimizerGRPC.SmartServiceImpl.internal_static_extrasmart_Goal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScheduleOptimizerGRPC.Goal.class, ScheduleOptimizerGRPC.Goal.Builder.class);
    }

    // Construct using ScheduleOptimizerGRPC.Goal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idealBalance_ = 0F;

      endDate_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ScheduleOptimizerGRPC.SmartServiceImpl.internal_static_extrasmart_Goal_descriptor;
    }

    @java.lang.Override
    public ScheduleOptimizerGRPC.Goal getDefaultInstanceForType() {
      return ScheduleOptimizerGRPC.Goal.getDefaultInstance();
    }

    @java.lang.Override
    public ScheduleOptimizerGRPC.Goal build() {
      ScheduleOptimizerGRPC.Goal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ScheduleOptimizerGRPC.Goal buildPartial() {
      ScheduleOptimizerGRPC.Goal result = new ScheduleOptimizerGRPC.Goal(this);
      result.idealBalance_ = idealBalance_;
      result.endDate_ = endDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ScheduleOptimizerGRPC.Goal) {
        return mergeFrom((ScheduleOptimizerGRPC.Goal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ScheduleOptimizerGRPC.Goal other) {
      if (other == ScheduleOptimizerGRPC.Goal.getDefaultInstance()) return this;
      if (other.getIdealBalance() != 0F) {
        setIdealBalance(other.getIdealBalance());
      }
      if (other.getEndDate() != 0L) {
        setEndDate(other.getEndDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ScheduleOptimizerGRPC.Goal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ScheduleOptimizerGRPC.Goal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float idealBalance_ ;
    /**
     * <code>float ideal_balance = 1;</code>
     */
    public float getIdealBalance() {
      return idealBalance_;
    }
    /**
     * <code>float ideal_balance = 1;</code>
     */
    public Builder setIdealBalance(float value) {
      
      idealBalance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float ideal_balance = 1;</code>
     */
    public Builder clearIdealBalance() {
      
      idealBalance_ = 0F;
      onChanged();
      return this;
    }

    private long endDate_ ;
    /**
     * <code>int64 end_date = 2;</code>
     */
    public long getEndDate() {
      return endDate_;
    }
    /**
     * <code>int64 end_date = 2;</code>
     */
    public Builder setEndDate(long value) {
      
      endDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 end_date = 2;</code>
     */
    public Builder clearEndDate() {
      
      endDate_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:extrasmart.Goal)
  }

  // @@protoc_insertion_point(class_scope:extrasmart.Goal)
  private static final ScheduleOptimizerGRPC.Goal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ScheduleOptimizerGRPC.Goal();
  }

  public static ScheduleOptimizerGRPC.Goal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Goal>
      PARSER = new com.google.protobuf.AbstractParser<Goal>() {
    @java.lang.Override
    public Goal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Goal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Goal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Goal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ScheduleOptimizerGRPC.Goal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

