// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTracker_GRPC;

public final class SmartServiceImpl {
  private SmartServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_TransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_TransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_TransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_TransactionRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_TransactionRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SpendingTracker.proto\022\013extra_smart\"6\n\022" +
      "TransactionRequest\022\016\n\006income\030\001 \001(\002\022\020\n\010sp" +
      "ending\030\002 \001(\002\"W\n\023TransactionResponse\022\017\n\007b" +
      "alance\030\001 \001(\002\022/\n\007records\030\002 \003(\0132\036.extra_sm" +
      "art.TransactionRecord\"F\n\021TransactionReco" +
      "rd\022\016\n\006income\030\001 \001(\002\022\020\n\010spending\030\002 \001(\002\022\017\n\007" +
      "balance\030\003 \001(\0022o\n\017SpendingTracker\022\\\n\021Reco" +
      "rdTransaction\022\037.extra_smart.TransactionR" +
      "equest\032 .extra_smart.TransactionResponse" +
      "\"\000(\0010\001B*\n\024SpendingTracker_GRPCB\020SmartSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extra_smart_TransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extra_smart_TransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_TransactionRequest_descriptor,
        new java.lang.String[] { "Income", "Spending", });
    internal_static_extra_smart_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extra_smart_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_TransactionResponse_descriptor,
        new java.lang.String[] { "Balance", "Records", });
    internal_static_extra_smart_TransactionRecord_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_extra_smart_TransactionRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_TransactionRecord_descriptor,
        new java.lang.String[] { "Income", "Spending", "Balance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
