// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTracker_GRPC;

/**
 * Protobuf type {@code extra_smart.TransactionRecord}
 */
public  final class TransactionRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:extra_smart.TransactionRecord)
    TransactionRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionRecord.newBuilder() to construct.
  private TransactionRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionRecord() {
    income_ = 0F;
    spending_ = 0F;
    balance_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            income_ = input.readFloat();
            break;
          }
          case 21: {

            spending_ = input.readFloat();
            break;
          }
          case 29: {

            balance_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SpendingTracker_GRPC.SmartServiceImpl.internal_static_extra_smart_TransactionRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SpendingTracker_GRPC.SmartServiceImpl.internal_static_extra_smart_TransactionRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SpendingTracker_GRPC.TransactionRecord.class, SpendingTracker_GRPC.TransactionRecord.Builder.class);
  }

  public static final int INCOME_FIELD_NUMBER = 1;
  private float income_;
  /**
   * <code>float income = 1;</code>
   */
  public float getIncome() {
    return income_;
  }

  public static final int SPENDING_FIELD_NUMBER = 2;
  private float spending_;
  /**
   * <code>float spending = 2;</code>
   */
  public float getSpending() {
    return spending_;
  }

  public static final int BALANCE_FIELD_NUMBER = 3;
  private float balance_;
  /**
   * <code>float balance = 3;</code>
   */
  public float getBalance() {
    return balance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (income_ != 0F) {
      output.writeFloat(1, income_);
    }
    if (spending_ != 0F) {
      output.writeFloat(2, spending_);
    }
    if (balance_ != 0F) {
      output.writeFloat(3, balance_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (income_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, income_);
    }
    if (spending_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, spending_);
    }
    if (balance_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, balance_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SpendingTracker_GRPC.TransactionRecord)) {
      return super.equals(obj);
    }
    SpendingTracker_GRPC.TransactionRecord other = (SpendingTracker_GRPC.TransactionRecord) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getIncome())
        == java.lang.Float.floatToIntBits(
            other.getIncome()));
    result = result && (
        java.lang.Float.floatToIntBits(getSpending())
        == java.lang.Float.floatToIntBits(
            other.getSpending()));
    result = result && (
        java.lang.Float.floatToIntBits(getBalance())
        == java.lang.Float.floatToIntBits(
            other.getBalance()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INCOME_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIncome());
    hash = (37 * hash) + SPENDING_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSpending());
    hash = (37 * hash) + BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBalance());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpendingTracker_GRPC.TransactionRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SpendingTracker_GRPC.TransactionRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code extra_smart.TransactionRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:extra_smart.TransactionRecord)
      SpendingTracker_GRPC.TransactionRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpendingTracker_GRPC.SmartServiceImpl.internal_static_extra_smart_TransactionRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpendingTracker_GRPC.SmartServiceImpl.internal_static_extra_smart_TransactionRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpendingTracker_GRPC.TransactionRecord.class, SpendingTracker_GRPC.TransactionRecord.Builder.class);
    }

    // Construct using SpendingTracker_GRPC.TransactionRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      income_ = 0F;

      spending_ = 0F;

      balance_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SpendingTracker_GRPC.SmartServiceImpl.internal_static_extra_smart_TransactionRecord_descriptor;
    }

    @java.lang.Override
    public SpendingTracker_GRPC.TransactionRecord getDefaultInstanceForType() {
      return SpendingTracker_GRPC.TransactionRecord.getDefaultInstance();
    }

    @java.lang.Override
    public SpendingTracker_GRPC.TransactionRecord build() {
      SpendingTracker_GRPC.TransactionRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public SpendingTracker_GRPC.TransactionRecord buildPartial() {
      SpendingTracker_GRPC.TransactionRecord result = new SpendingTracker_GRPC.TransactionRecord(this);
      result.income_ = income_;
      result.spending_ = spending_;
      result.balance_ = balance_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SpendingTracker_GRPC.TransactionRecord) {
        return mergeFrom((SpendingTracker_GRPC.TransactionRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SpendingTracker_GRPC.TransactionRecord other) {
      if (other == SpendingTracker_GRPC.TransactionRecord.getDefaultInstance()) return this;
      if (other.getIncome() != 0F) {
        setIncome(other.getIncome());
      }
      if (other.getSpending() != 0F) {
        setSpending(other.getSpending());
      }
      if (other.getBalance() != 0F) {
        setBalance(other.getBalance());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SpendingTracker_GRPC.TransactionRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SpendingTracker_GRPC.TransactionRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float income_ ;
    /**
     * <code>float income = 1;</code>
     */
    public float getIncome() {
      return income_;
    }
    /**
     * <code>float income = 1;</code>
     */
    public Builder setIncome(float value) {
      
      income_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float income = 1;</code>
     */
    public Builder clearIncome() {
      
      income_ = 0F;
      onChanged();
      return this;
    }

    private float spending_ ;
    /**
     * <code>float spending = 2;</code>
     */
    public float getSpending() {
      return spending_;
    }
    /**
     * <code>float spending = 2;</code>
     */
    public Builder setSpending(float value) {
      
      spending_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float spending = 2;</code>
     */
    public Builder clearSpending() {
      
      spending_ = 0F;
      onChanged();
      return this;
    }

    private float balance_ ;
    /**
     * <code>float balance = 3;</code>
     */
    public float getBalance() {
      return balance_;
    }
    /**
     * <code>float balance = 3;</code>
     */
    public Builder setBalance(float value) {
      
      balance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float balance = 3;</code>
     */
    public Builder clearBalance() {
      
      balance_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:extra_smart.TransactionRecord)
  }

  // @@protoc_insertion_point(class_scope:extra_smart.TransactionRecord)
  private static final SpendingTracker_GRPC.TransactionRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SpendingTracker_GRPC.TransactionRecord();
  }

  public static SpendingTracker_GRPC.TransactionRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionRecord>
      PARSER = new com.google.protobuf.AbstractParser<TransactionRecord>() {
    @java.lang.Override
    public TransactionRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public SpendingTracker_GRPC.TransactionRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

