// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTracker_GRPC;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extra_smart.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float balance = 1;</code>
   */
  float getBalance();

  /**
   * <code>float currentBalance = 2;</code>
   */
  float getCurrentBalance();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
