// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTracker_GRPC;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extra_smart.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float balance = 1;</code>
   */
  float getBalance();

  /**
   * <code>repeated .extra_smart.TransactionRecord records = 2;</code>
   */
  java.util.List<SpendingTracker_GRPC.TransactionRecord> 
      getRecordsList();
  /**
   * <code>repeated .extra_smart.TransactionRecord records = 2;</code>
   */
  SpendingTracker_GRPC.TransactionRecord getRecords(int index);
  /**
   * <code>repeated .extra_smart.TransactionRecord records = 2;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .extra_smart.TransactionRecord records = 2;</code>
   */
  java.util.List<? extends SpendingTracker_GRPC.TransactionRecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .extra_smart.TransactionRecord records = 2;</code>
   */
  SpendingTracker_GRPC.TransactionRecordOrBuilder getRecordsOrBuilder(
      int index);
}
