// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTracker_GRPC;

public interface TransactionRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extra_smart.TransactionRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float income = 1;</code>
   */
  float getIncome();

  /**
   * <code>float spending = 2;</code>
   */
  float getSpending();

  /**
   * <code>float balance = 3;</code>
   */
  float getBalance();
}
