// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduleOptimizer.proto

package ScheduleOptimizer_GRPC;

/**
 * Protobuf type {@code extra_smart.MonthlyGoal}
 */
public  final class MonthlyGoal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:extra_smart.MonthlyGoal)
    MonthlyGoalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MonthlyGoal.newBuilder() to construct.
  private MonthlyGoal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MonthlyGoal() {
    idealBalance_ = 0F;
    familyTime_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MonthlyGoal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            idealBalance_ = input.readFloat();
            break;
          }
          case 16: {

            familyTime_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ScheduleOptimizer_GRPC.SmartServiceImpl.internal_static_extra_smart_MonthlyGoal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ScheduleOptimizer_GRPC.SmartServiceImpl.internal_static_extra_smart_MonthlyGoal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ScheduleOptimizer_GRPC.MonthlyGoal.class, ScheduleOptimizer_GRPC.MonthlyGoal.Builder.class);
  }

  public static final int IDEAL_BALANCE_FIELD_NUMBER = 1;
  private float idealBalance_;
  /**
   * <code>float ideal_balance = 1;</code>
   */
  public float getIdealBalance() {
    return idealBalance_;
  }

  public static final int FAMILY_TIME_FIELD_NUMBER = 2;
  private int familyTime_;
  /**
   * <code>int32 family_time = 2;</code>
   */
  public int getFamilyTime() {
    return familyTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idealBalance_ != 0F) {
      output.writeFloat(1, idealBalance_);
    }
    if (familyTime_ != 0) {
      output.writeInt32(2, familyTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idealBalance_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, idealBalance_);
    }
    if (familyTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, familyTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ScheduleOptimizer_GRPC.MonthlyGoal)) {
      return super.equals(obj);
    }
    ScheduleOptimizer_GRPC.MonthlyGoal other = (ScheduleOptimizer_GRPC.MonthlyGoal) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getIdealBalance())
        == java.lang.Float.floatToIntBits(
            other.getIdealBalance()));
    result = result && (getFamilyTime()
        == other.getFamilyTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDEAL_BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIdealBalance());
    hash = (37 * hash) + FAMILY_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getFamilyTime();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScheduleOptimizer_GRPC.MonthlyGoal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ScheduleOptimizer_GRPC.MonthlyGoal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code extra_smart.MonthlyGoal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:extra_smart.MonthlyGoal)
      ScheduleOptimizer_GRPC.MonthlyGoalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduleOptimizer_GRPC.SmartServiceImpl.internal_static_extra_smart_MonthlyGoal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduleOptimizer_GRPC.SmartServiceImpl.internal_static_extra_smart_MonthlyGoal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScheduleOptimizer_GRPC.MonthlyGoal.class, ScheduleOptimizer_GRPC.MonthlyGoal.Builder.class);
    }

    // Construct using ScheduleOptimizer_GRPC.MonthlyGoal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idealBalance_ = 0F;

      familyTime_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ScheduleOptimizer_GRPC.SmartServiceImpl.internal_static_extra_smart_MonthlyGoal_descriptor;
    }

    @java.lang.Override
    public ScheduleOptimizer_GRPC.MonthlyGoal getDefaultInstanceForType() {
      return ScheduleOptimizer_GRPC.MonthlyGoal.getDefaultInstance();
    }

    @java.lang.Override
    public ScheduleOptimizer_GRPC.MonthlyGoal build() {
      ScheduleOptimizer_GRPC.MonthlyGoal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ScheduleOptimizer_GRPC.MonthlyGoal buildPartial() {
      ScheduleOptimizer_GRPC.MonthlyGoal result = new ScheduleOptimizer_GRPC.MonthlyGoal(this);
      result.idealBalance_ = idealBalance_;
      result.familyTime_ = familyTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ScheduleOptimizer_GRPC.MonthlyGoal) {
        return mergeFrom((ScheduleOptimizer_GRPC.MonthlyGoal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ScheduleOptimizer_GRPC.MonthlyGoal other) {
      if (other == ScheduleOptimizer_GRPC.MonthlyGoal.getDefaultInstance()) return this;
      if (other.getIdealBalance() != 0F) {
        setIdealBalance(other.getIdealBalance());
      }
      if (other.getFamilyTime() != 0) {
        setFamilyTime(other.getFamilyTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ScheduleOptimizer_GRPC.MonthlyGoal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ScheduleOptimizer_GRPC.MonthlyGoal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float idealBalance_ ;
    /**
     * <code>float ideal_balance = 1;</code>
     */
    public float getIdealBalance() {
      return idealBalance_;
    }
    /**
     * <code>float ideal_balance = 1;</code>
     */
    public Builder setIdealBalance(float value) {
      
      idealBalance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float ideal_balance = 1;</code>
     */
    public Builder clearIdealBalance() {
      
      idealBalance_ = 0F;
      onChanged();
      return this;
    }

    private int familyTime_ ;
    /**
     * <code>int32 family_time = 2;</code>
     */
    public int getFamilyTime() {
      return familyTime_;
    }
    /**
     * <code>int32 family_time = 2;</code>
     */
    public Builder setFamilyTime(int value) {
      
      familyTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 family_time = 2;</code>
     */
    public Builder clearFamilyTime() {
      
      familyTime_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:extra_smart.MonthlyGoal)
  }

  // @@protoc_insertion_point(class_scope:extra_smart.MonthlyGoal)
  private static final ScheduleOptimizer_GRPC.MonthlyGoal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ScheduleOptimizer_GRPC.MonthlyGoal();
  }

  public static ScheduleOptimizer_GRPC.MonthlyGoal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MonthlyGoal>
      PARSER = new com.google.protobuf.AbstractParser<MonthlyGoal>() {
    @java.lang.Override
    public MonthlyGoal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MonthlyGoal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MonthlyGoal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MonthlyGoal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ScheduleOptimizer_GRPC.MonthlyGoal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

