// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduleOptimizer.proto

package ScheduleOptimizer_GRPC;

public interface MonthlyGoalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extra_smart.MonthlyGoal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float ideal_balance = 1;</code>
   */
  float getIdealBalance();

  /**
   * <code>int32 family_time = 2;</code>
   */
  int getFamilyTime();
}
