// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduelOptimizer.proto

package ScheduleOptimizer_GRPC;

public final class SmartServiceImpl {
  private SmartServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_Goal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_Goal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_GoalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_GoalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ScheduelOptimizer.proto\022\013extra_smart\"/" +
      "\n\004Goal\022\025\n\rideal_balance\030\001 \001(\002\022\020\n\010end_dat" +
      "e\030\002 \001(\003\"0\n\014GoalResponse\022\017\n\007success\030\001 \001(\010" +
      "\022\017\n\007message\030\002 \001(\t2S\n\021ScheduleOptimizer\022>" +
      "\n\014SetChallenge\022\021.extra_smart.Goal\032\031.extr" +
      "a_smart.GoalResponse\"\000B,\n\026ScheduleOptimi" +
      "zer_GRPCB\020SmartServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extra_smart_Goal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extra_smart_Goal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_Goal_descriptor,
        new java.lang.String[] { "IdealBalance", "EndDate", });
    internal_static_extra_smart_GoalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extra_smart_GoalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_GoalResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
