// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduleOptimizer.proto

package ScheduleOptimizer_GRPC;

public final class SmartServiceImpl {
  private SmartServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_MonthlyGoal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_MonthlyGoal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extra_smart_GoalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extra_smart_GoalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ScheduleOptimizer.proto\022\013extra_smart\"9" +
      "\n\013MonthlyGoal\022\025\n\rideal_balance\030\001 \001(\002\022\023\n\013" +
      "family_time\030\002 \001(\005\"0\n\014GoalResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\\\n\021ScheduleO" +
      "ptimizer\022G\n\016SetMonthlyGoal\022\030.extra_smart" +
      ".MonthlyGoal\032\031.extra_smart.GoalResponse\"" +
      "\000B,\n\026ScheduleOptimizer_GRPCB\020SmartServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extra_smart_MonthlyGoal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extra_smart_MonthlyGoal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_MonthlyGoal_descriptor,
        new java.lang.String[] { "IdealBalance", "FamilyTime", });
    internal_static_extra_smart_GoalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extra_smart_GoalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extra_smart_GoalResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
