// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTrackerGRPC;

public final class SmartServiceImpl {
  private SmartServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrasmart_TransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrasmart_TransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrasmart_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrasmart_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SpendingTracker.proto\022\nextrasmart\"6\n\022T" +
      "ransactionRequest\022\016\n\006income\030\001 \001(\002\022\020\n\010spe" +
      "nding\030\002 \001(\002\"O\n\023TransactionResponse\022\017\n\007ba" +
      "lance\030\001 \001(\002\022\026\n\016currentBalance\030\002 \001(\002\022\017\n\007m" +
      "essage\030\003 \001(\t2m\n\017SpendingTracker\022Z\n\021Recor" +
      "dTransaction\022\036.extrasmart.TransactionReq" +
      "uest\032\037.extrasmart.TransactionResponse\"\000(" +
      "\0010\001B)\n\023SpendingTrackerGRPCB\020SmartService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extrasmart_TransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extrasmart_TransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrasmart_TransactionRequest_descriptor,
        new java.lang.String[] { "Income", "Spending", });
    internal_static_extrasmart_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extrasmart_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrasmart_TransactionResponse_descriptor,
        new java.lang.String[] { "Balance", "CurrentBalance", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
