// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTrackerGRPC;

public interface TransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extrasmart.TransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float income = 1;</code>
   */
  float getIncome();

  /**
   * <code>float spending = 2;</code>
   */
  float getSpending();
}
