// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpendingTracker.proto

package SpendingTrackerGRPC;

/**
 * Protobuf type {@code extrasmart.TransactionRequest}
 */
public  final class TransactionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:extrasmart.TransactionRequest)
    TransactionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionRequest.newBuilder() to construct.
  private TransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionRequest() {
    income_ = 0F;
    spending_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            income_ = input.readFloat();
            break;
          }
          case 21: {

            spending_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SpendingTrackerGRPC.SmartServiceImpl.internal_static_extrasmart_TransactionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SpendingTrackerGRPC.SmartServiceImpl.internal_static_extrasmart_TransactionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SpendingTrackerGRPC.TransactionRequest.class, SpendingTrackerGRPC.TransactionRequest.Builder.class);
  }

  public static final int INCOME_FIELD_NUMBER = 1;
  private float income_;
  /**
   * <code>float income = 1;</code>
   */
  public float getIncome() {
    return income_;
  }

  public static final int SPENDING_FIELD_NUMBER = 2;
  private float spending_;
  /**
   * <code>float spending = 2;</code>
   */
  public float getSpending() {
    return spending_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (income_ != 0F) {
      output.writeFloat(1, income_);
    }
    if (spending_ != 0F) {
      output.writeFloat(2, spending_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (income_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, income_);
    }
    if (spending_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, spending_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SpendingTrackerGRPC.TransactionRequest)) {
      return super.equals(obj);
    }
    SpendingTrackerGRPC.TransactionRequest other = (SpendingTrackerGRPC.TransactionRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getIncome())
        == java.lang.Float.floatToIntBits(
            other.getIncome()));
    result = result && (
        java.lang.Float.floatToIntBits(getSpending())
        == java.lang.Float.floatToIntBits(
            other.getSpending()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INCOME_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIncome());
    hash = (37 * hash) + SPENDING_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSpending());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpendingTrackerGRPC.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SpendingTrackerGRPC.TransactionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code extrasmart.TransactionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:extrasmart.TransactionRequest)
      SpendingTrackerGRPC.TransactionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpendingTrackerGRPC.SmartServiceImpl.internal_static_extrasmart_TransactionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpendingTrackerGRPC.SmartServiceImpl.internal_static_extrasmart_TransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpendingTrackerGRPC.TransactionRequest.class, SpendingTrackerGRPC.TransactionRequest.Builder.class);
    }

    // Construct using SpendingTrackerGRPC.TransactionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      income_ = 0F;

      spending_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SpendingTrackerGRPC.SmartServiceImpl.internal_static_extrasmart_TransactionRequest_descriptor;
    }

    @java.lang.Override
    public SpendingTrackerGRPC.TransactionRequest getDefaultInstanceForType() {
      return SpendingTrackerGRPC.TransactionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public SpendingTrackerGRPC.TransactionRequest build() {
      SpendingTrackerGRPC.TransactionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public SpendingTrackerGRPC.TransactionRequest buildPartial() {
      SpendingTrackerGRPC.TransactionRequest result = new SpendingTrackerGRPC.TransactionRequest(this);
      result.income_ = income_;
      result.spending_ = spending_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SpendingTrackerGRPC.TransactionRequest) {
        return mergeFrom((SpendingTrackerGRPC.TransactionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SpendingTrackerGRPC.TransactionRequest other) {
      if (other == SpendingTrackerGRPC.TransactionRequest.getDefaultInstance()) return this;
      if (other.getIncome() != 0F) {
        setIncome(other.getIncome());
      }
      if (other.getSpending() != 0F) {
        setSpending(other.getSpending());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SpendingTrackerGRPC.TransactionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SpendingTrackerGRPC.TransactionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float income_ ;
    /**
     * <code>float income = 1;</code>
     */
    public float getIncome() {
      return income_;
    }
    /**
     * <code>float income = 1;</code>
     */
    public Builder setIncome(float value) {
      
      income_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float income = 1;</code>
     */
    public Builder clearIncome() {
      
      income_ = 0F;
      onChanged();
      return this;
    }

    private float spending_ ;
    /**
     * <code>float spending = 2;</code>
     */
    public float getSpending() {
      return spending_;
    }
    /**
     * <code>float spending = 2;</code>
     */
    public Builder setSpending(float value) {
      
      spending_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float spending = 2;</code>
     */
    public Builder clearSpending() {
      
      spending_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:extrasmart.TransactionRequest)
  }

  // @@protoc_insertion_point(class_scope:extrasmart.TransactionRequest)
  private static final SpendingTrackerGRPC.TransactionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SpendingTrackerGRPC.TransactionRequest();
  }

  public static SpendingTrackerGRPC.TransactionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransactionRequest>() {
    @java.lang.Override
    public TransactionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public SpendingTrackerGRPC.TransactionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

